### ISSUE TITLE
More information in the readme

### ISSUE THREAD

**Issue by con-ssc** [jlattimer/CRMVSCodeJSSnippets#1]
Hello Jason,
it would be really nice if you could add some more information in the extension description so ppl know what snippets are in the package.

**Comment by jlattimer** [comment]
Good idea - should be able to generate a list easy enough

**Comment by jlattimer** [comment]
Added some additional detail to the readme but the bulk of the data now is on a wiki page

**Comment by con-ssc** [comment]
Much better.
