### ISSUE TITLE
Code snippets also for Visual Studio 2015

### ISSUE THREAD

**Issue by con-ssc** [jlattimer/CRMVSCodeJSSnippets#4]
Is it possible to also make the snippets available for visual studio 2015?

**Comment by jlattimer** [comment]
As part of my CRM Developer Extensions (https://visualstudiogallery.msdn.microsoft.com/0f9ab063-acec-4c55-bd6c-5eb7c6cffec4) , I have the same JS snippets - albeit with different shortcut names. I think I'll revamp them to match what I've done here. This would probably happen in conjunction with the update I'll need to do when CRM 8.2 ships in a few weeks.
