### ISSUE TITLE
should we convert the json file to xml to be able to insert into VS? or we can just insert json snippet? 

### ISSUE THREAD

**Issue by chunxiao1** [jlattimer/CRMVSCodeJSSnippets#5]

**Comment by jlattimer** [comment]
I think you'd end up with a lot of work converting the JSON to XML to get it into the proper format for Visual Studio. 

I've actually already done this though as part of my CRM Developer Extensions: https://marketplace.visualstudio.com/items?itemName=JLattimer.DynamicsCRMDeveloperExtensions

**Comment by chunxiao1** [comment]
Thanks a lot. Working now.

发件人: Jason Lattimer [mailto:notifications@github.com]
发送时间: Tuesday, December 27, 2016 1:27 PM
收件人: jlattimer/CRMVSCodeJSSnippets <CRMVSCodeJSSnippets@noreply.github.com>
抄送: chunxiao1 <chunxiao.lin@hotmail.com>; Author <author@noreply.github.com>
主题: Re: [jlattimer/CRMVSCodeJSSnippets] should we convert the json file to xml to be able to insert into VS? or we can just insert json snippet? (#5)


I think you'd end up with a lot of work converting the JSON to XML to get it into the proper format for Visual Studio.

I've actually already done this though as part of my CRM Developer Extensions: https://marketplace.visualstudio.com/items?itemName=JLattimer.DynamicsCRMDeveloperExtensions
